### PR TITLE
[feat] Add testing section in PR template

### PR DESCRIPTION
**Pull request by SammyBaek**
## Changes made
This PR adds two sections in a PR template
- Tests ran
- Tests added

## Screencapture (if applicable)

image

### CODE REVIEW

**Review by EpicPi — COMMENTED** [review]
What does this mean?
Like locally tested e2e? 
Why would you need to locally run unit tests? Wouldn't ci just do that for you?

**Comment by SammyBaek** [comment]
> What does this mean? Like locally tested e2e?

Yes, to make sure that the feature works from user standpoint.

> Why would you need to locally run unit tests? Wouldn't ci just do that for you?

lol very true, did not think about this. Should we change it to the tix title on notion? i.e. `tests added` `tests done manually`

**Comment by EpicPi** [comment]
I don't think the "added unit tests" check box is necessary - since it'll be self evident in the pr - and the reviewer can prompt the author to add the tests if necessary.
The locally tested e2e would be good tho.

**Review by EpicPi — APPROVED** [review]
lgtm

**Pull request merged**
